spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fazpramim?createDatabaseIfNotExist=true
    username: root
    password: berenice
  jackson:
    default-property-inclusion: non_null
