security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fazpramim?createDatabaseIfNotExist=true
    username: root
    password: berenice
#    password: 1234
  jackson:
    default-property-inclusion: non_null
  mvc:
    path match:
      matching-strategy: ant_path_matcher
spring-doc:
  paths-to-match:
    - /api/users/**
    - /auth/**
    - /api/registration
    - /api/services/**
  swagger-ui:
    use-root-path: true
